import os
import subprocess
import sys
import argparse
from rich.console import Console

# Ensure imports work from project root
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from src.utils.paths import get_profile_paths

console = Console()

def cleanup_aux_files(folder_path, filename):
    """Removes aux/log files to ensure a clean build."""
    base = os.path.splitext(filename)[0]
    for ext in ['.aux', '.log', '.out']:
        f = os.path.join(folder_path, base + ext)
        if os.path.exists(f):
            try:
                os.remove(f)
            except OSError:
                pass

def print_latex_log_error(log_file):
    """Reads the .log file generated by latex to find the error."""
    if not os.path.exists(log_file):
        console.print("[red]      (No .log file found. Did pdflatex run?)[/red]")
        return

    with open(log_file, 'r', errors='replace') as f:
        lines = f.readlines()
    
    console.print("[dim]      --- TAIL OF LOG FILE ---[/dim]")
    found_error = False
    for i, line in enumerate(lines):
        if line.startswith('!'):
            console.print(f"[bold red]      {line.strip()}[/bold red]")
            if i+1 < len(lines): console.print(f"      {lines[i+1].strip()}")
            found_error = True
    
    if not found_error and len(lines) > 0:
        console.print(f"      {lines[-2].strip() if len(lines) > 1 else ''}")
        console.print(f"      {lines[-1].strip()}")

def compile_latex(folder_path, filename):
    tex_file = os.path.join(folder_path, filename)
    if not os.path.exists(tex_file): return

    # Clean previous run artifacts
    cleanup_aux_files(folder_path, filename)

    console.print(f"   ⚙️  Compiling {filename}...", end="")

    try:
        result = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", filename], 
            cwd=folder_path, 
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            timeout=30 # Safety timeout for compilation
        )

        if result.returncode == 0:
            console.print("[green] ✅ Success[/green]")
        else:
            console.print("[red] ❌ Failed[/red]")
            log_file = os.path.join(folder_path, filename.replace('.tex', '.log'))
            print_latex_log_error(log_file)
    except subprocess.TimeoutExpired:
        console.print("[red] ❌ Timeout (pdflatex hung)[/red]")
    except FileNotFoundError:
        console.print("[red] ❌ Error: pdflatex command not found.[/red]")

def run(profile_name):
    paths = get_profile_paths(profile_name)
    app_dir = os.path.join("data", "applications", profile_name) # Ensure correct path construction

    if not os.path.exists(app_dir):
        console.print(f"[red]❌ No application directory found at: {app_dir}[/red]")
        return

    subfolders = [f.path for f in os.scandir(app_dir) if f.is_dir()]
    
    if not subfolders:
        console.print(f"[yellow]No generated applications found in {app_dir}[/yellow]")
        return

    console.print(f"[bold cyan]📄 Compiling PDFs for [white]{profile_name}[/white]...[/bold cyan]")
    
    for folder in subfolders:
        folder_name = os.path.basename(folder)
        console.print(f"\n[bold cyan]📂 {folder_name}[/bold cyan]")
        
        compile_latex(folder, "resume.tex")
        compile_latex(folder, "cover.tex")
    
    console.print(f"\n[dim]Outputs located in: {app_dir}[/dim]")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=str, required=True, help="Profile name")
    args = parser.parse_args()
    
    run(args.profile)
