import os
import subprocess
import sys
from rich.console import Console

console = Console()
APPLICATIONS_DIR = "data/applications"

print("--- DEBUG MODE ACTIVE: IF YOU SEE THIS, THE CODE UPDATED ---")

def print_latex_log_error(log_file):
    """Reads the .log file generated by latex to find the error."""
    if not os.path.exists(log_file):
        console.print("[red]      (No .log file found. Did pdflatex run?)[/red]")
        return

    with open(log_file, 'r', errors='replace') as f:
        lines = f.readlines()
    
    console.print("[dim]      --- TAIL OF LOG FILE ---[/dim]")
    # Print lines starting with ! (errors) or the last 10 lines
    found_error = False
    for i, line in enumerate(lines):
        if line.startswith('!'):
            console.print(f"[bold red]      {line.strip()}[/bold red]")
            # Print context lines
            if i+1 < len(lines): console.print(f"      {lines[i+1].strip()}")
            found_error = True
    
    if not found_error:
        # If no strict error found, print the last few lines
        for line in lines[-10:]:
            console.print(f"      {line.strip()}")

def compile_latex(folder_path, filename):
    tex_file = os.path.join(folder_path, filename)
    if not os.path.exists(tex_file): return

    console.print(f"   ⚙️  Compiling {filename}...", end="")

    # Force run, do not hide output completely
    result = subprocess.run(
        ["pdflatex", "-interaction=nonstopmode", filename], 
        cwd=folder_path, 
        stdout=subprocess.DEVNULL, # Hide standard output
        stderr=subprocess.PIPE     # Capture errors
    )

    if result.returncode == 0:
        console.print("[green] ✅ Success[/green]")
    else:
        console.print("[red] ❌ Failed[/red]")
        # Check the log file for the specific error
        log_file = os.path.join(folder_path, filename.replace('.tex', '.log'))
        print_latex_log_error(log_file)

def run():
    if not os.path.exists(APPLICATIONS_DIR): return
    subfolders = [f.path for f in os.scandir(APPLICATIONS_DIR) if f.is_dir()]
    
    for folder in subfolders:
        console.print(f"\n[bold cyan]📂 {os.path.basename(folder)}[/bold cyan]")
        compile_latex(folder, "resume.tex")
        compile_latex(folder, "cover.tex")

if __name__ == "__main__":
    run()
